//key for return [<li key="1>...</li>, <li key="2">..</li>]
import React, { Component } from 'react';
import { connect } from 'react-redux';
import { Link } from 'react-router-dom';
import Payments from './Payments';
import "materialize-css/dist/css/materialize.min.css";
import "materialize-css/dist/js/materialize.min.js";

/**
 *https://materializecss.com/navbar.html
 */
export class Header extends Component { // eslint-disable-line react/prefer-stateless-function
 renderContent() {
   switch (this.props.auth) { //user model is available as this.props.auth
     case null:
      return;
     case false:
      return (
        <li><a href="/auth/google">Login With Google</a></li>
      );
     default:
      return [
        <li key="1"><Payments /></li>,
        <li key="4">
         <div className="valign-wrapper">
           Credits:<span className="badge yellow">{ this.props.auth.credits }</span>
         </div>
        </li>,
        <a href="/" key="2" className="waves-effect waves-light btn-small blue"><i className="material-icons right">cloud</i>Add Credits</a>,
        <li key="3"><a href="/api/logout">Logout</a></li>

      ];
   }
 }

  render() {
    return (
     <nav>
        <div className="nav-wrapper">
          <Link
            to={this.props.auth ? '/surveys' : '/'}
            className="left brand-logo"
          >
            Emaily
          </Link>
          <ul className="right">
            {this.renderContent()}
          </ul>
        </div>
      </nav>
    );
  }
}

// function mapStateToProps(state) {
// //object, pass to the Header as props
// //property,auth for authReducer in /reducers/index.js
//   return{ auth: state.auth}; //auth property is generated by state.auth
// }
function mapStateToProps({ auth }) {
//return object, pass the object to the Header as props
//property,auth for authReducer in /reducers/index.js
  return{ auth }; //auth property is generated by state.auth
}
export default connect(mapStateToProps)(Header);
